tracker-width: 640
tracker-height: 384
gpu-id: 0
ll-lib-file: /opt/nvidia/deepstream/deepstream-6.0/lib/libnvds_nvmultiobjecttracker.so
ll-config-file: /opt/nvidia/deepstream/deepstream-6.0/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
enable-batch-process: 1
enable-past-frame: 1
input-tensor-meta: 1

useUniqueID: 1

useColorNames: 0
enableOpticalFlow: 1
enableBatchProcessing: 1
